danilowoz/react-content-loader

README.md
Congratz for this awesome project 😸
=> Fix typo in README.md "Our -> Or"

README.md, src/Wrap.js, src/index.js, tests/index.js
@danilowoz Width was locked at 400px. It is possible to calculate a good heigh to match this for aspect ratio, but it would be even better to simply be able to set a custom width. This PR addresses that.
=> Allow custom width

src/index.js
@bahaa96 after your PR, I was thinking that I should to implement the `defaultProps` too. 
Today I am not happy with the approach to how default values is defined.
What do you think about of this change? Is better?
=> Implemented defaultProps

.babelrc, .flowconfig, package-lock.json, package.json, src/Wrap.js, src/custom/Circle.js, src/custom/Rect.js, src/index.js, src/stylized/CodeStyle.js, src/stylized/FacebookStyle.js, src/stylized/InstagramStyle.js, src/stylized/ListStyle.js
=> Setup flow and convert existing component files 

README.md, src/Wrap.js, src/index.js
SVG can now get preserveAspectRatio attribute from props.
=> added preserveAspectRatio To props

README.md
=> Fixing #39

README.md
@danilowoz I had removed `--save-dev` and forgot to let it as `--save`. Can you review this later?
Thanks.
=> Adding --save switch

src/index.js
It is related to this issue:
https://github.com/danilowoz/react-content-loader/issues/44
Sometimes it is necessary to change width and other params of content loader. For example when we resize the window.
=> Removed state from ContentLoader component

README.md, src/Wrap.js, src/index.js, src/stylized/BulletListStyle.js, src/stylized/CodeStyle.js, src/stylized/FacebookStyle.js, src/stylized/InstagramStyle.js, src/stylized/ListStyle.js, stories/index.js, tests/index.js
**THIS IS A BREAKING CHANGE, REQUIRES A MAJOR BUMP**
fixes #69
=> Added named exports and removed type prop

.gitignore, package-lock.json, package.json, tests/Wrap.js, tests/index.js, tests/stylized/BulletListStyle.js, tests/stylized/CodeStyle.js, tests/stylized/FacebookStyle.js, tests/stylized/InstagramStyle.js, tests/stylized/ListStyle.js, tests/uid.js, yarn.lock
@enapupe what do you think? Does that make sense?
=> Improvement tests

README.md, src/Wrap.js, src/index.js, stories/index.js, tests/Wrap.js, tests/index.js
* Allow control speed animation with a prop
* If the prop not passed `true` is default
=> Control speed animation

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This pull request will add templates for opening issues and pull requests. Templates standardize the information given in pull requests and issues.
=> Templates for pull requests and issues

README.md
This adds `vue-content-loader` to the README.
=> Add vue-content-loader

package-lock.json, package.json, tests/Wrap.js, tests/index.js, tests/stylized/BulletListStyle.js, tests/stylized/CodeStyle.js, tests/stylized/FacebookStyle.js, tests/stylized/InstagramStyle.js, tests/stylized/ListStyle.js, tests/uid.js
I remove all unused imports from tests.
No issue related.
Not included a break changes.
=> remove all unused imports from tests

src/Wrap.js, stories/index.js, tests/index.js
That allows removing the viewBox and other things
Related #107
=> feat(Wrap): Destruct options in component

README.md, package.json, src/Holder.js, src/Svg.js, tests/index.js
=> feat(a11y): Add title and aria label

src/Holder.tsx, src/index.ts
See the description of the related Issue #131
=> Named default export of Holder.tsx.

README.md
* Fixed preserveAspectRatio options url.
* Add new similar Angular package.
None.
No.
=> chore(readme): fix url and add new similar package

README.md
Hey, I exported your library using bit so people can now:
- Find and install the component in bit.dev.
- Play with the examples and edit the code.
- See all the tests in each component.
- Install each component individually instead of installing all the project.
- Import component in their project to modify the code locally if needed.
- See all dependencies.
- See bundle size of the component before installing it.
I'll be happy to continue and update the collection, and/or I can hand over ownership of the collection if you prefer.
Thanks
=> Update README.md/added bit components

src/native/Svg.tsx
=> fix(native): remove listener on unmont

package-lock.json, package.json, src/__tests__/dependency.test.tsx, src/native/package.json
=> fix(dependencies): move native dependencies to native module

README.md
small change to readme to show reacteurope badge
=> add reacteurope badge to readme

README.md, docs/index.stories.tsx, package-lock.json, src/index.ts, src/native/Svg.tsx, src/native/interface.ts
=> fix(Interface): extend svg attr

package.json
=> fix(interface): path to interface declaration

README.md
=> docs(README): fix "Black box in Safari / iOS"

package.json, src/native/Svg.tsx
=> fix(native): creates the styles obj using assign

README.md
=> docs(troubleshooting): browser support

package.json
=> fix(package): adjust peer dependency to support React 17

README.md
A typo fixes in README.md file.
Not applicable.
Not applicable.
- [] Are all the test cases passing?
- [] If any new feature has been added, then are the test cases updated/added?
- [] Has the documentation been updated for the proposed change, if required?
=> docs(README): fix a typo in README.md

package.json
Should fix https://github.com/danilowoz/react-content-loader/issues/320
=> fix(exports): starts path with ./
